image: "gableroux/unity3d:2018.1.3f1"

stages:
- test
# - build
- deploy

variables:
  BUILD_NAME: ExampleProjectName

.unity_before_script: &unity_before_script
  before_script:
  - mkdir -p /root/.cache/unity3d
  - mkdir -p /root/.local/share/unity3d/Unity/
  - echo "$UNITY_LICENSE_CONTENT" | tr -d '\r' > /root/.local/share/unity3d/Unity/Unity_lic.ulf

.test: &test
  stage: test
  <<: *unity_before_script
  script: |
    xvfb-run --auto-servernum --server-args='-screen 0 640x480x24' \
      /opt/Unity/Editor/Unity \
        -projectPath $(pwd) \
        -batchmode \
        -runTests \
        -logFile \
        -testResults $(pwd)/$TEST_PLATFORM-results.xml \
        -testPlatform $TEST_PLATFORM
    UNITY_EXIT_CODE=$?
    if [ $UNITY_EXIT_CODE -eq 0 ]; then
      echo "Run succeeded, no failures occurred"
    else if [ $UNITY_EXIT_CODE -eq 2 ]; then
      echo "Run succeeded, some tests failed"
    else if [ $UNITY_EXIT_CODE -eq 3 ]; then
      echo "Run failure (other failure)"
    else
      echo "Unexpected exit code $UNITY_EXIT_CODE"
    fi
    cat ./$TEST_PLATFORM-results.xml | grep test-run | grep Passed
    exit $UNITY_TEST_EXIT_CODE
  artifacts:
    paths:
      - ./$TEST_PLATFORM-results.xml

test-editmode:
  <<: *test
  variables:
    TEST_PLATFORM: editmode

test-playmode:
  <<: *test
  variables:
    TEST_PLATFORM: playmode

.build: &build
  # stage: build
  stage: test # reusing same stage to do everything in parallel reduces overall time
  <<: *unity_before_script
  script: |
    echo "Building for $BUILD_TARGET"
    export BUILD_PATH=./Builds/$BUILD_TARGET/
    mkdir -p $BUILD_PATH
    xvfb-run --auto-servernum --server-args='-screen 0 640x480x24' \
      /opt/Unity/Editor/Unity \
      -projectPath $(pwd) \
      -quit \
      -batchmode \
      -buildTarget $BUILD_TARGET \
      -customBuildTarget $BUILD_TARGET \
      -customBuildName $BUILD_NAME \
      -customBuildPath $BUILD_PATH \
      -customBuildOptions AcceptExternalModificationsToPlayer \
      -executeMethod BuildCommand.PerformBuild \
      -logFile
    ls -la $BUILD_PATH
    [ -n "$(ls -A $BUILD_PATH)" ] # fail job if build folder is empty
  
  artifacts:
    paths:
    - ./Builds/
#uncomment following lines if you'd like to build only on master branch
#   only:
#     - master

build-StandaloneLinux64:
  <<: *build
  variables:
    BUILD_TARGET: StandaloneLinux64

build-StandaloneOSX:
  <<: *build
  variables:
    BUILD_TARGET: StandaloneOSX

#For versions < 2017.2:
# build-StandaloneOSXUniversal:
#   <<: *build
#   variables:
#     BUILD_TARGET: StandaloneOSXUniversal

build-StandaloneWindows64:
  <<: *build
  variables:
    BUILD_TARGET: StandaloneWindows64

build-WebGL:
  <<: *build
  variables:
    BUILD_TARGET: WebGL

pages:
  image: alpine:latest
  stage: deploy
  script:
  - mv ./Builds/WebGL public
  artifacts:
    paths:
    - public
  only:
  - master
